CHAT_ID = "chat_id"
SCHEDULE = "schedule"
APP_PASSWORD = "app_password"
GMAIL_ADDRESS = "gmail_address"
MODULE_IS_ON = "module_is_on"
SET_COMMAND = "$set"
ID = "_id"

SCHEDULE_SESSIONS = "schedule_sessions"
GMAIL_SESSIONS = "gmail_sessions"
STUDENT_BOT = "student_bot"
